### ISSUE TITLE
Support for contradicting parameters && multiple parameters that must be provided together

### ISSUE THREAD

**Issue by yannisklonatos** [scopt/scopt#10]
Hello,

I find scopt to be a very efficient tool for CLI parsing in Scala. Two features I would like to see included in scopt (if they do not already exist of course) are:

1) Support for contradicting parameters. E.g. I have a case where I cannot use -c and -d (for example) together at the same time, but currently I have to parse this requirement myself.
2) Support for parameters that must ALL be provided. For instance I have a case where when I provide -a argument, -b -c and -d arguments must be provided. Again I must manually check if all of them are satisfied. 

This is just an idea to make scopt even greater!

Cheers,

**Comment by eed3si9n** [comment]
I haven't use it, but [scallop](https://github.com/Rogach/scallop/wiki/Arguments-validation) already provides this feature. Do you want to give that a spin, and tell me if it's a good replacement of scopt?
