### ISSUE TITLE
Scala 2.12 milestones support

### ISSUE THREAD

**Issue by slandelle** [scopt/scopt#100]
Hi there,

Is there any plan to publish cross built versions for the Scala 2.12 milestones?

Regards

**Comment by eed3si9n** [comment]
+1
a bit busy this week with Lightbend eng meeting, but I will do this next week.

**Comment by slandelle** [comment]
Great, thanks!
Note that you'll have to upgrade to latest specs2 3.7, I don't think you'll ever get specs 2.3 builds for Scala 2.12.

**Comment by slandelle** [comment]
Thanks!
