### ISSUE TITLE
Unit-versus-Boolean, negation options

### ISSUE THREAD

**Issue by javabrett** [scopt/scopt#101]
A couple of related issues here - I searched the issues back-catalog but haven't found anything similar yet.

I'm working on some code that defines a `Unit` option e.g. `--some-setting` and uses it to set an `Option[Boolean]` to `Some(true)`.  Some other options also imply this option, so later `someSetting.getOrElse(...` is used for that logic.

The question is: what it the best way to offer a `--no-some-setting` option, to allow the implied behavior from the other options to be overridden?  I've seen in the examples that `Unit` options are offered with a `--not-keep-alive`, which is explicitly-coded, and this is certainly works.

In looking at this I am trying to understand the difference and advantage of using a `Boolean` option, other than that the type matches, and it forces a more explicit true/false value to be entered on the command-line.  Instead of hand-coding both `--some-setting` and `--no-some-setting` as `Unit`, I thought `--some-setting` as `Boolean` could work, allowing `--some-setting:0` or `--some-setting:false` as simple explicit negation of the option.  The downside is that this also forces `--some-setting:1` instead of a simple `--some-setting`, as I don't think the `Boolean` option allows a default-when-present to be enabled set (would always be true really).

So what is best:
- Come up with a way to (optionally?) relax a `Boolean` option, such that present-no-value can imply `true`?
- Design some auto-negation pair for a `Unit` option?
- Neither, just accept that you need to code a positive/negative pair for an optional boolean-style option?

Thanks
Brett

**Comment by eed3si9n** [comment]
I think it depends on the application and the kind of option on how it should be coded. The current simple solution "just code it yourself" affords many solutions without scopt being prescriptive. For example, you're using `Option[Boolean]` as a three-way value, which is cool.
