### ISSUE TITLE
Support literal dash (-) as an argument

### ISSUE THREAD

**Issue by drekbour** [scopt/scopt#108]
Common command-line practice is to use `-` as a placeholder for stdin. I can't see any way to achieve this with scopt.

```
echo hello | myapp - targetURL
Error: Unknown option -
```

**Comment by drekbour** [comment]
Workaround is use an internal substitute before parsing

```
def main(args: Array[String]) {
  val args108 = args.map { case "-" => "STDIN"; case x => x}
  parser.parse(args108, Config()) match {
```

**Comment by frgomes** [comment]
So, when hyphen "-" is found (i.e.: without anything following it!) simply stop the logic involved on identifying the `opt[A]` and abandon this option, leaving all command line parameters untouched for this iteration. Later, when looking for `arg[A]`, the hyphen "-" will be found as well as all other arguments remaining in the list of parameters and will be returned as any other argument. The application will recognize the hyphen "-" possibly as a file name and, in this special case, the application is responsible for reading from STDIN.

**Comment by drekbour** [comment]
Yes, I think that summarises it.

**Comment by omervk** [comment]
+1 to this. Really missing it from scopt.
