### ISSUE TITLE
Potential OSGi support

### ISSUE THREAD

**Issue by briantopping** [scopt/scopt#126]
Hi there,

I'm considering a conversion of a project that boots with ScOpt to OSGi. If it takes off, I'm considering that the project could remain transparent to deployment (whether in a `main()` method or as a bundle in a container) by having ScOpt read from OSGi Configuration Admin if it were detected.

Before writing anything, I wanted to discover if a clean patch for this kind of thing would be accepted. Just trying to lay out options for my client.

Thanks! Brian

**Comment by eed3si9n** [comment]
What does that exactly entail for scopt?
OSGi library dependency and some configuration delegation code?
Would that mean all projects that uses scopt would start pulling in OSGi? Currently scopt has zero dependencies, and I'd be careful in introducing any dependencies.

The only possibility I think that the utility outweighs the cost of introducing a dependency would be fallback to Typesafe Conifg (https://github.com/scopt/scopt/issues/89).

A potential compromise might be to implement a facade for configurations and keep integration to OSGi or other configuration files in a separate project.

**Comment by briantopping** [comment]
Great points, thanks for thinking this through together!

As you mention it, I'd make sure OSGi core was an optional dependency. Under normal circumstances, this would make sure that there would be no packaging changes. Users that wanted the functionality would include the jar on their classpath, but they would have it already anyway in such a usage, so packaging changes for them would also be zero.

Most of my goal was emulating what is necessary from the command line, for instance in a clustered environment and either being a seed node or locating them. In production environments, this is usually node-dependent and best localized on the specific machines rather than having than depending on heuristics such as IP address. Of course there are many ways to skin the cat, this just reduces the pathways through the client code of scopt so both deployments can use the same bootstrap pattern.

**Comment by briantopping** [comment]
I'll take it a different direction, thanks for considering it.
