### ISSUE TITLE
cross-build for scalajs

### ISSUE THREAD

**Issue by aappddeevv** [scopt/scopt#135]
With node.js becoming a good platform for running scalajs, provide a scalajs version of scopt, otherwise we have to use commander or yargs or do something else.

**Comment by aappddeevv** [comment]
I forked it and reworked the project to allow scalajs to work although it needs some more playtime.

https://github.com/aappddeevv/scopt.git

**Comment by xuwei-k** [comment]
- https://github.com/scopt/scopt/pull/141
- http://repo1.maven.org/maven2/com/github/scopt/scopt_sjs0.6_2.12/

**Comment by eed3si9n** [comment]
This was fixed in https://github.com/scopt/scopt/pull/137 by @aappddeevv
