### ISSUE TITLE
Add a generic lift of scopt.Read[T] into scopt.Read[Option[T]]

### ISSUE THREAD

**Issue by wbazant** [scopt/scopt#145]
I came here from the Ammonite project. :) I wanted to add an optional ammonite.opspath as an argument to my script, and ended up needing to provide my own parser which seems unnecessary.

I looked into the internals and found the project had
```
implicit def pathRead: scopt.Read[Path] = scopt.Read.stringRead.map{(Path(_, pwd))}
```

And to get the code to work I needed to add the following to my script:
```
implicit def optionPathRead: scopt.Read[Option[Path]] = scopt.Read.stringRead.map{case "" => None ; case str => Some(Path(str, pwd))}
```

I haven't looked at scopt's code or tried to do this but I feel it could be possible to give it a generic converter from scopt.Read[T] into scopt.Read[Option[T]].

Do you think it's a good idea to have one?
Do you think adding one is within the limits of scopt's codebase and the Scala language?

**Comment by morgen-peschke** [comment]
It's fairly trivial to [implement](https://github.com/scopt/scopt/pull/158), if it's a good idea or not is another question entirely.

Are you trying to enable something like this?
```bash
$ some-command --prefix= --sep=, --suffix='>' a b c d e f
a,b,c,d,e,f>
```

**Comment by wbazant** [comment]
No, not at all! I tried my option parser to model the arguments provided from the point of "what was actually provided". The problem I tried to solve was for a script that read a TSV file of which the first column was identifiers, did something with the data, and you could optionally pass it an "id to name" file that resulted in an extra column. It's not making my script "do one thing well" but it was convenient at the time.

I wanted "no decoration file provided" to correspond to "do not add an extra column". So it didn't really make sense to have a default decoration file, or a default value of ammonite.ops.Path that was  a null object, or something like that.

Is it a good idea- the benefit: it will let the user of scopt require a parameter Option[R] just by saying that's what it should be. Say, an Option[String] to distinguish between no option value provided, and an empty string provided as an option value. 

Why it is perhaps not - I am not sure what's the scenario when someone has a parser for R (either custom or one of the default ones), specifies Option[R] as desired option type, and wants something else than the behaviour your PR is adding.

**Comment by morgen-peschke** [comment]
Well, an `opt[Option[String]](...)` won't distinguish between omitted and passing an empty string.

An `opt[String]` mapping into a config value which is an `Option[String]` _could_ produce `None`, `Option("")` and `Option("...")`.

As to the scenario when a different behavior is desired, the default behavior is easy enough to override by having an different `Read` in scope, or provided implicitly.

**Comment by eed3si9n** [comment]
A generic Read might not make sense unless it gives rise to a corresponding syntax to express it.

See https://github.com/scopt/scopt/blob/scopt3/shared/src/main/scala/scopt/options.scala#L71-L104

We have `Read[(A1, A2)]` to parse `key=value`. `None` expressed as empty string (does that actually work with current parser?) feels too subtle. It might be worth looking into existing well known commandline apps that does similar thing.

**Comment by wbazant** [comment]
String is maybe an unfortunate example because there is a natural "null" object "". My use case that prompted the issue was a Path argument, that wasn't required in my script and also didn't have a natural default.

Most languages have a null/undef, and in the old style parsing like argparse in bash you set some defaults, iterate over an options object, and populate the arguments in a big switch statement, so that an argument will be null if not populated.

I propose None expressed as not specifying the value at all. Compare `prog.scala --foo="" --bar=baz` vs `prog.scala --bar=baz`. If foo is specified as an Option[String] , I propose the first case to parse as Some("") and second as None.

**Comment by morgen-peschke** [comment]
@eed3si9n : I added some tests to confirm that the current behavior is to pass through an empty string unchanged.

As far as syntax goes, `Read[Option[A]]` ignoring the empty string or delegating a non-empty value seems pretty intuitive.

@wbazant : I used `String` as that's the natural representation of the incoming data, so it's really the only incoming type we have to consider before the decision to delegate to the `Read[T]` that's being lifted to `Read[Option[T]]`.

Currently your proposed behavior is the default, and is how it will parse in the following example:
```
case class Config(pathOpt: Option[Path] = None)

implicit val pathRead: Read[Path] = ...

val parser = new scopt.OptionParser[Config]("example") {
  opt[Path]('p').action((p, c) => c.copy(pathOpt = Some(p)))
}
```

**Comment by wbazant** [comment]
Thank you for adding the tests and working on this feature request!

I see why you talked about Strings now  I thought I'd have a harder time verbalizing the difference between not passing an argument and passing an empty argument on example of Strings,and why anyone might want that distinction, because "" is a natural default so maybe Option[String] won't be used often, whereas an optional version of a type lacking a similar natural default might come up more frequently.

**Comment by morgen-peschke** [comment]
@wbazant That makes sense. 

Frankly, it's still a bit of an issue as the class encoding the config still needs to represent non-existence somehow. `Option` works well generally, but it's a bit awkward to have a field with is required have an type which indicates optionality. 

What I'd love is some mechanism to have the input config and output config be of different types. Maybe `checkConfig` could be modified so `success` contains a value, it could look vaguely like this:

```
case class ConfigBuilder(pathOpt: Option[Path] = None)
case class Config(path: Path)

val parser = new scopt.OptionParser[ConfigBuilder, Config]("example") {
  opt[Path]('p').action((p, c) => c.copy(pathOpt = Some(p)))

  checkConfig {
    case ConfigBuilder(None) => missingRequiredOpt('p') // helper to trigger the same error message as a missing opt[](...).required()
    case ConfigBuilder(Some(p)) if !Files.canRead(p) => failure("path must be readable")
    case ConfigBuilder(Some(p)) => Config(p)
  }
}
```
