### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by drdozer** [scopt/scopt#16]
Is there a pattern for validating option/argument values? The type of the action is (String, C) => C, so there's no way to tell the parser that a value is wrong and then have it explain why and print out usage. The simplest botch would be:

``` scala
(String, C) => Either[String, C] // left as error
```

However, something that explicitly names the cases would probably be better:

``` scala
sealed trait ActionValue[C]
case class Failure[C](msg: String) extends ActionValue[C]
case class Success[C](c: C) extends ActionValue[C]

// may not need this
case class Warning[C](msg: String, c: C) extends ActionValue[C]
```

There are other ways to do this, obviously. I just don't like having the value validation miles away from the parsing in the sourcecode.

**Comment by eed3si9n** [comment]
Currently scopt doesn't implement any sort of value validation. I think [Rogach/scallop](https://github.com/Rogach/scallop) does, so you can try that out. If it doesn't work for whatever reason, we can take a look at it again.

**Comment by ziggystar** [comment]
Is there any reasoning behind the decision to make `Reader` of type `String => A` instead of `String => Validation[A]`? So are there any arguments against the validation approach, beside the additional work?

And would you accept pull-requests to add this feature?
