### ISSUE TITLE
sbt test failing with "(scoptNative/nativetest:nativeLinkNIR) unable to link" error

### ISSUE THREAD

**Issue by YugandhaD** [scopt/scopt#164]
Hi,

I am trying to build top of the tree version of scopt, on linux platform.
Scala version: 2.12.4
sbt version: 1.0.3

I tried to build & test scopt with following commands:
`sbt compile`
`sbt test`

Here,
`sbt compile` command works, but `sbt test` command fails with following error:
__________________________________________________________________________________________________
**[info]   cmd("update") hidden() children(opt[Unit]("foo").text("foo")) should
[info]     + print usage text
[info]
[info]   terminationSafeParser should
[info]     + not terminate on `--help`
[info]     + not terminate on `--version`
[info]
[info]   emptyParser.showUsage
[info]     + print empty usage text
[info]
[info] Total for specification ImmutableParserSpec
[info] Finished in 3 seconds, 22 ms
[info] 111 examples, 0 failure, 0 error
[info]
[info] Passed: Total 177, Failed 0, Errors 0, Passed 177
[error] unable to link
[error] (scoptNative/nativetest:nativeLinkNIR) unable to link
[error] Total time: 9 s, completed Dec 28, 2017 1:10:46 PM**
__________________________________________________________________________________________________

In between, it also gives following error:
**cannot link: @org.specs2.runner.Specs2Framework
cannot link: @org.specs2.runner.Specs2Framework::init**

When I try same, with scopt v3.6.0, the tests pass without any issues.
Am I missing something?
Any help to resolve the issue would be appreciated.

**Comment by javabrett** [comment]
You might need to use `sbt` version `0.13.16` for now. 
 Give that a try anyway.  See https://github.com/scopt/scopt/blob/scopt3/project/build.properties#L1 .

**Edit**: the problem does not reproduce for me with `sbt 1.0.3`, so maybe it is something else.  Travis build is passing.

**Comment by YugandhaD** [comment]
Hi @javabrett, I could resolve it. I used sbt version 0.13.16,.
I had multiple clang installations, so corrected it and instead of using `sbt test` directly, I followed the way used in the travis job as follows:
`export TEST_PROJECT="scoptJVM"`
`sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "project $TEST_PROJECT" test`

This resolved my issue. 
Thanks for the quick help.
