### ISSUE TITLE
Partial Parsing of command line.

### ISSUE THREAD

**Issue by ravindrabajpai** [scopt/scopt#168]
case class TimeoutLauncherCLI(appTimeOut: FiniteDuration = 0 minute,
                              appName: String = "",
                              appUser: String = "",
                              allOtherArgs: Array[String] = Array(""))

I want to build an object of TimeoutLauncherCLI from the command line, basically, I need to take only 3 parameters from the command line (appTimeOut, appname, and appuser). Rest I want to pass down to another module, so I don't need to parse or validate.

I wonder how this can be done using scopt, or if there is any other standard library. Please suggest.

**Comment by frgomes** [comment]
You can have the "remaining arguments" after a separator, say for example: "--".
Your application first finds "--" and pass everything on the left of that to scopt, just like you are used to. Everything on the right of "--" you keep and pass to the other module.

Have a look at the sources below, at line 62:
https://github.com/frgomes/scala-bindgen/blob/master/bindgen/src/main/scala/Main.scala

**Comment by eed3si9n** [comment]
If you just want to grab the first three arguments, I am not sure if you need scopt at all.
Just convert the argument to List and check the length or something.
Other possibility could be using something like https://github.com/scala/scala-parser-combinators for partial parsing.

**Comment by ravindrabajpai** [comment]
@frgomes: This will work if I have control over the user, what if a user changes the order. With command line, they can do that!!

@eed3si9n I thought scopt would like to have this feature if it is not there already. Otherwise, currently, I am doing the same thing as you have suggested.
