### ISSUE TITLE
Allow Strings for short options

### ISSUE THREAD

**Issue by pdalpra** [scopt/scopt#19]
In scopt 2.10, we had the ability to use Strings for short options but, since scopt 3.0, short options are Chars, limiting short options to a single character.

Could it be possible to bring back Strings for short options ?

If you're OK with it, I could provide a PR for this change.

**Comment by eed3si9n** [comment]
I personally think all short options should be a single character, otherwise it shouldn't use `-`.
Do you have some examples that can convince me otherwise?
Also note scopt3 supports option grouping.

**Comment by pdalpra** [comment]
In Gatling, the project where we're trying to migrate to scopt3, we have a bunch of options which would lead to some "collision" if we were to use a single character.
Here is the list of short and long options for one of our main classes : https://github.com/excilys/gatling/blob/master/gatling-app/src/main/scala/io/gatling/app/CommandLineConstants.scala

Here, if we were to use a single character, differentiating `--simulation`, `--simulations-folder` and `--simulations-binaries-folder` short options would prove very difficult :
- We would keep `-s`for `--simulation`
- We couldn't change `--simulations-binaries-folder` to `-b` for example : what to do of `--request-bodies-folder` ? use `-r` ? It would then block `-results-folder`, etc...
- As you can see, `-f` won't do :)

And even if we managed to find a combination of letters which would make sense, it would probably mean changing most , if not all, of our command line options...

**Comment by eed3si9n** [comment]
Still not too convinced, but I don't really have a good argument to be draconian about single char rule besides my preference, so maybe I should be more open.
I still want options to be grouped, so if I allow string in short options, it would need to implement greedy algorithm. In other words, if there are options `-a`, `-b`, `-c` and `-bc`, `-abc` needs to parse to `-a` and `-bc`.

**Comment by slandelle** [comment]
I see your point regarding grouping.
The API break is annoying, but I guess we'll have to cope with it...

**Comment by eed3si9n** [comment]
scopt 3.1 is out with the change.

**Comment by slandelle** [comment]
Thanks a lot! We'll upgrade ASAP.
