### ISSUE TITLE
What does action and copy method do?

### ISSUE THREAD

**Issue by ohmycloud** [scopt/scopt#197]
there are  code like `.action((x, c) => c.copy(conf = x)` everywhere, but the document or help about this two methods is lack,  the source code of `action` and `copy` looks too much hard for first glance.

**Comment by andrea-rockt** [comment]
the simplified signatures are

```
scopt.OptionParser[A]

option[B](???)

action[B]((B, A) => A)

type Read[A] = (String) => A

```

`A` is the data structure that you want to parse to
`B` is the type of the option you are gonna parse

if A is a case class it will have a generated copy method for it

so 

when an option is 
```
case class MyConfigClass(value: Int)

object Parser: scopt:OptionParser[MyConfigClass] {

      opt[Int]('v',"value).action( (b: Int, a: MyConfigClass) => a.copy(value = b))

}


val zero: MyConfigClass = MyConfigClass(0)
val args : Array[String] = Seq("-v", "5")
val parsed : MyConfigClass = Parser.parse(args, zero)


parsed != zero
parsed == MyConfigClass(5)
```

The flow is

the library will parse MyConfigClass from command line

MyConfigClass begin as MyConfigClass(0)

when an option -v or --value is encountered a Read[Int] = s:String => Int.parse(s) will be used to transform a String in Int then action will be invoked like having as parameters

```
(5, MyConfigClass(0))  
```

the responsibility of the lambda inside action is to copy the `5` in the value slot of MyConfigCLass

**Comment by ohmycloud** [comment]
thanks for clarify.
