### ISSUE TITLE
OptionParser opt -- type argument?

### ISSUE THREAD

**Issue by Sciss** [scopt/scopt#2]
When I came across this question (http://stackoverflow.com/questions/9893075/using-the-help-method-in-the-immutable-scopt-scala-optionparser-2-0-1), I looked into the `OptionParser` class, and it occured to me that the `opt` method with three arguments wrongly has a type parameter `C`. Shouldn't it just take `C` from the enclosing class?

**Comment by eed3si9n** [comment]
Apologies for the delayed response. I didn't notice that org owners don't automatically get issues notifications.

> Shouldn't it just take `C` from the enclosing class?

Yes
