### ISSUE TITLE
Publish 2.13.0-M5

### ISSUE THREAD

**Issue by ashawley** [scopt/scopt#204]
Waiting on minitest, see https://github.com/monix/minitest/issues/23, which in turn is waiting on ScalaCheck.

**Comment by ashawley** [comment]
Changes in #208.

**Comment by Sciss** [comment]
Please publish to Maven Central: https://search.maven.org/search?q=scopt_2.13.0-M5

**Comment by eed3si9n** [comment]
Done https://github.com/scopt/scopt/releases/tag/v3.7.1
