### ISSUE TITLE
Travis matrix

### ISSUE THREAD

**Issue by ashawley** [scopt/scopt#209]
Confusion about the Travis build came up in #207.  It's better, now that there isn't special sauce necessary for building test dependencies.

It is strange that there are 17 builds, when there should be 18.

It only builds native with oraclejdk8, and not also with openjdk11.  Granted, this seems like a feature rather than a bug.

|   Java          |   Scala       |  Scala.js  |  Native   |
|-----------------|---------------|------------|-----------|
|   oraclejdk8    |   2.10.7      |            |           |
|   oraclejdk8    |   2.10.7      |   0.6.23   |           |
| ~~oraclejdk8~~  | ~~2.10.7~~    |            | ~~0.3.8~~ |
|   oraclejdk8    |   2.11.12     |            |           |
|   oraclejdk8    |   2.11.12     |   0.6.23   |           |
|   oraclejdk8    |   2.11.12     |            |   0.3.8   |
|   oraclejdk8    |   2.12.7      |            |           |
|   oraclejdk8    |   2.12.7      |   0.6.23   |           |
| ~~oraclejdk8~~  | ~~2.12.7~~    |            | ~~0.3.8~~ |
|   oraclejdk8    |   2.13.0-M3   |            |           |
|   oraclejdk8    |   2.13.0-M3   |   0.6.23   |           |
| ~~oraclejdk8~~  | ~~2.13.0-M3~~ |            | ~~0.3.8~~ |
|   oraclejdk11   |   2.10.7      |            |           |
|   oraclejdk11   |   2.10.7      |   0.6.23   |           |
| ~~oraclejdk11~~ | ~~2.10.7~~    |            | ~~0.3.8~~ |
|   oraclejdk11   |   2.11.12     |            |           |
|   oraclejdk11   |   2.11.12     |   0.6.23   |           |
|   oraclejdk11   |   2.11.12     |            |   0.3.8   |
|   oraclejdk11   |   2.12.7      |            |           |
|   oraclejdk11   |   2.12.7      |   0.6.23   |           |
| ~~oraclejdk11~~ | ~~2.12.7~~    |            | ~~0.3.8~~ |
|   oraclejdk11   |   2.13.0-M3   |            |           |
|   oraclejdk11   |   2.13.0-M3   |   0.6.23   |           |
| ~~oraclejdk11~~ | ~~2.13.0-M3~~ |            | ~~0.3.8~~ |

**Comment by eed3si9n** [comment]
At this point in time, I am only interested in the runtime behavior under JDK11, so I am not sure if building using JDK11 would add much to testing to Scala.js or Scala Native.

**Comment by eed3si9n** [comment]
In other words, the combination should be something like:

|   Scala          |   Target runtime       |
|-----------------|---------------|
|   2.10.7    |   OpenJDK8 / OpenJDK11 / Scala.js 0.6 |
|   2.11.12    |   OpenJDK8 / OpenJDK11 / Scala.js 0.6 / Native     |
|   2.12.8    |   OpenJDK8 / OpenJDK11 / Scala.js 0.6     |
|   2.13.0-M5    |   OpenJDK8 / OpenJDK11 / Scala.js 0.6     |

**Comment by ashawley** [comment]
I think the remaining confusion is there is an `include` entry for Native on Scala 2.11, but it is only run on JDK8 even though the Travis config semantics might suggest otherwise. As you point out, it's a happy accident.

**Comment by eed3si9n** [comment]
I think https://github.com/scopt/scopt/blob/develop/.github/workflows/ci.yml is much simpler now.
