### ISSUE TITLE
Possible Scala 2.13 regression - Seq semantics changed

### ISSUE THREAD

**Issue by Sciss** [scopt/scopt#218]
So now unqualified

    def parse(args: Seq[String], init: C): Option[C]

suddently means

    def parse(args: scala.collection.immutable.Seq[String], init: C): Option[C]

And consequently the standard case of passing in the `Array[String]` from `main` creates a problem:

```
Warning:(61, 30) method copyArrayToImmutableIndexedSeq in class LowPriorityImplicits2 is deprecated (since 2.13.0): Implicit conversions from Array to immutable.IndexedSeq are implemented by copying; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
  val config  = parser.parse(args, Config()) getOrElse sys.exit(1)
```

So it should probably be qualified as `scala.collection.Seq` to match Scala 2.11 and 2.12 behaviour.

**Comment by eed3si9n** [comment]
Sounds good. Would you like to send a PR for this?

**Comment by eed3si9n** [comment]
I just sent https://github.com/scopt/scopt/pull/221
