### ISSUE TITLE
how to print brief usage

### ISSUE THREAD

**Issue by tksk** [scopt/scopt#22]
I want to print brief usage without "--help" option instead of full usage text.
e.g. `tar(1)` performs that:

``` shell
$ tar some wrong options
tar: invalid option -- 'e'
Try `tar --help' or `tar --usage' for more information.
```

how to build an OptionParser for this.

**Comment by eed3si9n** [comment]
You can probably override 

``` scala
  def reportError(msg: String) {
    Console.err.println("Error: " + msg)
  }
```

Print whatever you want to, and then `sys.exit` out in there.

**Comment by eed3si9n** [comment]
Or you can send me a pull req:

``` scala
def showUsageOnError: Boolean = true
```

and use that, in 

``` scala
    if (_error) {
      showUsage
      None
    }
```

**Comment by eed3si9n** [comment]
Brief messaging would be the default behavior on 3.2.0 when `help("help")` is defined.
