### ISSUE TITLE
"sys.exit" causes SBT interactive mode to terminate

### ISSUE THREAD

**Issue by Zahnentferner** [scopt/scopt#23]
sys.exit causes the SBT interactive mode to terminate. Would it be possible to change this behavior?
### steps
1. run "sbt" to enter SBT's interactive mode.
2. define `fullRunInputTask(InputKey[Unit]("my_run"), Runtime, "org.myorg.MyMain")` in build.sbt
3. within SBT's interactive mode, execute "my_run --help"
### problem

This will:
- show the usage text (desirable)
- exit the application invoked by "run --help" (desirable)
- exit SBT's interactive method (undesirable)
### expectation

In my opinion, SBT's interactive mode shouldn't be exited.

**Comment by eed3si9n** [comment]
I thought other people may have similar issue, so Googled it and found a stackoverflow question: [SBT stop run without exiting](http://stackoverflow.com/questions/5137460/sbt-stop-run-without-exiting). Seth's answer on using forking should apply here too.

**Comment by eed3si9n** [comment]
Actually which version of sbt are you using? I can actually call `run --help` without shutting down sbt 0.12.4.

**Comment by Zahnentferner** [comment]
I'm using SBT 0.12.1...

Actually, `run --help` also works fine for me indeed. My original description of the issue was a bit imprecise. Sorry for that.

If you define custom run tasks in build.sbt by adding a line such as: 

```
fullRunInputTask(InputKey[Unit]("my_run"), Runtime, "org.myorg.MyMain")
```

and then execute `my_run --help`,  you can observe the behaviour I described (i.e. SBT termination). 

Defining custom run tasks in build.sbt is useful when the project has more than one main class.

Setting `fork in run := true` does not solve the issue in this case. Even if it did solve, I don't think it would be the most elegant solution possible. Ideally, scopt should exit more smoothly. `sys.exit` seems like a very abrupt way of exiting. 

The following alternative definition of `help` displays the usage message and exits smoothly without terminating SBT:

``` scala
  def help(name: String): OptionDef[Unit, C] =
    opt[Unit](name) validate { _ => failure("") }
```

The disadvantage is that it prints "Error: " before displaying the usage message, because of the pseudo validation failure. Ideally, it would be nice if scopt could provide a ```help''' method that would exit smoothly as the alternative version above does, but without relying on such a conceptually ugly hack that forces a validation failure when there is actually nothing to be validated.

Thanks! Best regards!

**Comment by eed3si9n** [comment]
I am open to exploring alternative form of exiting programs, but one way or the other wouldn't `sys.exit` be called eventually? Since `run` task is able to trap exits currently, you can lobby and/or send pull req to sbt so `fullRunInputTask` does the same. That'll be more consistent and beneficial to other programs beyond scopt.

**Comment by Zahnentferner** [comment]
Thanks for creating the issue in SBT's repo. I lobbied there, as you suggested. A more uniform treatment of standard and custom run tasks is definitely needed in SBT.

However, I still feel that there is something non-elegant and maybe conceptually wrong about calling `sys.exit` in scopt.  According to (http://www.scala-lang.org/api/current/index.html#scala.sys.package), `sys.exit` causes the whole JVM to exit.  So, if I have other processes running in the same JVM as scopt, scopt's `sys.exit` will force the termination of all these other processes.

Apparently, SBT executes default run tasks in a separate JVM (and thus is not terminated by scopt), but custom run tasks in the same JVM (and thus is terminated by scopt). Asking the SBT developers to execute custom run tasks also in a separate JVM would solve the particular issue described above, but scopt's ``sys.exit` would still cause problems whenever scopt is called in the same JVM where other processes are being executed.

Anyway, this is a low-priority issue... Just be aware that `sys.exit` is just hiding and waiting to cause more problems for you in the future.

Once again, thank you very much for scopt! It is a very nice command line parser.
