### ISSUE TITLE
Cannot parse negative numbers

### ISSUE THREAD

**Issue by Sciss** [scopt/scopt#239]
E.g.

```scala
object ScoptTest {
  def main(args: Array[String]): Unit = {
    val p = new scopt.OptionParser[Unit]("Test") {
      opt[String]('n', "name")
      arg[Double]("value")
    }
    p.parse(args, ())
  }
}
```

If I run that with `args = Array("-3.1415926")`, I get

```
Error: Unknown option -3.1415926
Error: Missing argument value
Usage: Test [options] value

  -n, --name <value>  
  value               
```

How do I make this work? Is it a bug?

**Comment by eed3si9n** [comment]
I think it's a bug.
http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

> 6. Unless otherwise specified, whenever an operand or option-argument is, or contains, a numeric value:
> ...
> - When the utility description states that it accepts negative numbers as operands or option-arguments, numerals in the range -2147483647 to 2147483647 are syntactically recognized as numeric values.

so we should fix the parsing logic to not treat -3.1415926 as a number, not an option.

**Comment by Sciss** [comment]
I guess the checks are

- https://github.com/scopt/scopt/blob/scopt3/shared/src/main/scala/scopt/options.scala#L526
- https://github.com/scopt/scopt/blob/scopt4/shared/src/main/scala/scopt/ORunner.scala#L329

I can make a pull request; is scopt3 still ok, or just scopt4 being developed?

**Comment by eed3si9n** [comment]
Both would be welcomed.

**Comment by Sciss** [comment]
Ah, can't really get IntelliJ to like the cross project and/or minitest. Giving up for now. Note that the linked commit does _not_ fix the issue.

**Comment by avdv** [comment]
Hi.

IMHO, this fix is not the best thing to do.

Firstly, the section quoted from https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html only defines something about *operands* and *option arguments*, but nothing about options themselves.

Secondly, they say:
> Each option name should be a single alphanumeric character (the alnum character classification) from the portable character set.

So, you can basically have several "numeric" flags, represented by single digits. And
 
> One or more options without option-arguments, followed by at most one option that takes an option-argument, should be accepted when grouped behind one '-' delimiter.

Now, with this change, this no longer works:
```console
$ cmd -1 -2 -3
OK
$ cmd -123
ERROR: no such option
# and a bit more surprising...
$ cmd -A1
OK
$ cmd -1A
ERROR: no such option
```

I would like to suggest that the parser tries to parse options, and if there is an ambiguity between whether something is an option or not, ie. when an operand starts with a dash, the user should have to stop option parsing with `--` explicitly.

BTW, this is how the GNU `getopt` function works. WDYT?

**Comment by eed3si9n** [comment]
So if we want to support `-1` as option arguments, short option, and argument (operand) it would need to support:

```
$ cmd --name -1 -1 -- -1
```

?

**Comment by avdv** [comment]
Yes, exactly.

I think supporting `--` to stop option parsing should be done anyway, since it's kind of the status quo and otherwise you cannot use arguments (operands) that "look like flags" -- negative numbers only being a special case of this.
