### ISSUE TITLE
showUsage writes to Console.err

### ISSUE THREAD

**Issue by Zahnentferner** [scopt/scopt#24]
## steps 
1. execute "run --help"
## problem
1. prints the usage text in Console.err
## expectation

Since there is nothing erroneous about calling "run --help", I  expect the usage text to be written to Console.out  instead.  Only when there is a validation failure, I would expect the usage text to be written to Console.err .

Thanks!

**Comment by eed3si9n** [comment]
That makes sense. [GNU Coding Standards](http://www.gnu.org/prep/standards/standards.html#g_t_002d_002dhelp):

> The standard `--help` option should output brief documentation for how to invoke the program, on standard output, then exit successfully. Other options and arguments should be ignored once this is seen, and the program should not perform its normal function.

Along with this, I might not stop displaying the entire usage text on parsing failure, and use shorter message mentioned in #22.
