### ISSUE TITLE
multiple occurrence does not work on 4.0.0 RC2

### ISSUE THREAD

**Issue by marcadella** [scopt/scopt#249]
Let's suppose the parser definition is `opt[String]("i")`
If I submit with `--i abc --i def` I get:
```
Error: Unknown option --i
Error: Unknown argument 'def'
```
Same issue with `arg`.

**Comment by avdv** [comment]
You can use `.unbounded()` on an option / arg to make the parser accept it more than once. See https://github.com/scopt/scopt/issues/277#issuecomment-841664448
