### ISSUE TITLE
RFE: Allow "Pass-through" of errors and Console messages

### ISSUE THREAD

**Issue by grkuntzmd** [scopt/scopt#25]
Add an option to allow errors and usage messages to be returned instead writing directly to the Console. This will allow unit tests to confirm that bad options are properly handled.

**Comment by xuwei-k** [comment]
Is this helpful to you?
https://github.com/scopt/scopt/pull/18/files#L1R400

`scala.Console` has [`withErr`](https://github.com/scala/scala/blob/v2.10.2/src/library/scala/Console.scala#L157-L167)

**Comment by grkuntzmd** [comment]
## That might work. Thanks.

G. Ralph Kuntz, MD, MS

If you invent a technology that is "idiot proof," someone will invent a better idiot.

**Comment by eed3si9n** [comment]
You can override `reportError` and `reportWarning` and do anything you want in there. I'm assuming I can close this case.

**Comment by grkuntzmd** [comment]
Yes. That sounds good.
