### ISSUE TITLE
Publish for 2.13.0

### ISSUE THREAD

**Issue by ashawley** [scopt/scopt#251]
Please publish scopt 3.7.1 for 2.13.0.

**Comment by lihaoyi** [comment]
FWIW this is blocking Ammonite from 2.13.0

**Comment by tOverney** [comment]
How would such a PR look like? Is there just an update against `scopt4` needed or all branches?

**Comment by eed3si9n** [comment]
Last I checked I couldn't run tests because macro-compat wasn't available - https://github.com/milessabin/macro-compat/issues/86

**Comment by eed3si9n** [comment]
I was actually able to workaround this by locally publishing macro-compat with some whatever version number. 3.7.1 should sync to Maven Central soon. - https://oss.sonatype.org/content/repositories/public/com/github/scopt/scopt_2.13/

**Comment by lihaoyi** [comment]
Thanks @eed3si9n !

**Comment by milessabin** [comment]
Please see the discussion here: https://github.com/milessabin/macro-compat/pull/85#issuecomment-500201690.

By all means maintain your own fork, but seriously folks ... you don't need it, just ditch macro-compat altogether.

**Comment by eed3si9n** [comment]
yea. I didn't have time to look into the Minitest code last night to remove macro-compat, but now I'm motivated to roll my own uTest / Minitest and put it into the standard library.
