### ISSUE TITLE
Using logger with scopt

### ISSUE THREAD

**Issue by Zejnilovic** [scopt/scopt#255]
Hello. Is there a way to use scopt and logger together? Currently, when something goes wrong it just goes
```
Error: Unknown argument ... 
```

I would like to see 

```
19/07/04 12:59:51 ERROR: Unknown argument ...
```

**Comment by eed3si9n** [comment]
As noted in https://github.com/scopt/scopt/pull/260, this should be handled using `runEffects(...)` - https://github.com/scopt/scopt#abstracting-over-effects
