### ISSUE TITLE
Release 4.0

### ISSUE THREAD

**Issue by Zejnilovic** [scopt/scopt#262]
As per our the conversation we had with @eed3si9n I am opening a ticket for the release of scopt 4.0 and it's general planing so it is open to the wider public. 

@eed3si9n, if you have any "must have" solved issue before the release please post them. I believe the community will love to chime in and help.

From my side, I would love to see the #255 finished.

## Todo before stable 4.0 can be released (please edit and add)
- [ ] #255 add logging option
- [ ] others ...

**Comment by eed3si9n** [comment]
I created a milestone for 4.0.0 too - https://github.com/scopt/scopt/milestone/1
Maybe it's related to what you want with logger, but I'd like an API that isolates all effects and returns a sequence of data structure (#263) inspired by @lbialy's comment on my blog post - http://disq.us/p/1ylm4p8

**Comment by eed3si9n** [comment]
Once we have #263, making scopt report to a logger would be done by a single pattern match.

**Comment by eed3si9n** [comment]
It took a while but 4.0.0 is now out.
