### ISSUE TITLE
access to other args in validation functions

### ISSUE THREAD

**Issue by zero-sum** [scopt/scopt#27]
Is there a way to allow validation functions access to other arguments?

For instance, if there is an arg specifying an "output file" I could evaluate it more accurately during validation if I was aware that option "--overwriteExisting" were also set.

**Comment by eed3si9n** [comment]
How would it look like?

``` scala
arg[File]("<file>...") unbounded() optional() action { (x, c) =>
    c.copy(files = c.files :+ x) } text("optional unbounded args") validateWithConfig { (x, c) =>
      if (c.overwriteExisting) failure("The file doesn't exist")
      else success
    }
```

Something like the above?

**Comment by zero-sum** [comment]
Perfect!  

Only one question -- could precedence (e.g. the arg depends on the opt already having been parsed) be handled simply by the order in which they are defined in the parser declaration? Or would some sort of internal DAG need to be used.

**Comment by eed3si9n** [comment]
The way it works now is that they are processed in the order it was passed, so you'd need to use `Option[T]` or something to track options and validate them when all are filled in.

**Comment by zero-sum** [comment]
Not exactly sure how this would work.  Maybe I am misunderstanding something?

`".. -overwriteExisting <file> .."`
`-overwriteExisting` will be set to either None or Some[Boolean], enabling validation of `<file>`
`".. <file> -overwriteExisting .."  // preferred usage`
`-overwriteExisting` will not be set at the time of file validation.  `<file>` could be validated during `-overwriteExisting` validation, but only if `-overwriteExisting` (which is optional) is used

I can think of a couple solutions:
- Provide the ability for a final validation pass after all args have been parsed
- Define `-overwriteExisting` as a child of `<file>`, and then enforce processing of of children before processing of parent.  e.g.

``` scala
arg[File]("<output path>")
  .text("The output location")
  .children(
    opt[Unit]("overwrite") 
    abbr("o")   
    action { (_, c) => c.copy(overwriteOutputPath = false) } 
    text("overwrite output path")
  )
  .action { (x, c) => c.copy(outputPath = x) }
  .validateWithConfig{ (x,c) => // perform file validation using c.overwriteExisting }

```

**Comment by eed3si9n** [comment]
Added a standalone `checkConfig` construct. This can also be nested within `children`.

``` scala
val parser = new scopt.OptionParser[Config]("scopt") {
  head("scopt", "3.x")
  opt[Unit]('k', "keepalive") action { (x, c) =>
    c.copy(keepalive= true) }
  opt[Boolean]("xyz") action { (x, c) =>
    c.copy(xyz = x) } text("xyz is a boolean property"),
  checkConfig { c =>
    if (c.keepalive && c.xyz) failure("xyz cannot keep alive") else success }
}
```

It's available as 3.2.0-SNAPSHOT if you wanna give it a shot.

**Comment by eed3si9n** [comment]
3.2.0 is out.

**Comment by zero-sum** [comment]
Thanks, works great.
