### ISSUE TITLE
Cannot use scopt 3.2.0 with maven

### ISSUE THREAD

**Issue by aalexandrov** [scopt/scopt#28]
It seems that the new Scopt version (3.2.0) is still not pushed to the [Maven Repository](http://mvnrepository.com/artifact/com.github.scopt/scopt_2.10). Are there any plans to do that?

**Comment by slandelle** [comment]
Forget about mvnrepository.com, use search.maven.org.
Scopt 3.2.0 is properly deployed in maven central: http://search.maven.org/#search%7Cga%7C1%7Cscopt

**Comment by aalexandrov** [comment]
Thanks!

**Comment by eed3si9n** [comment]
Thanks @slandelle
