### ISSUE TITLE
Scopt 4 is not binary compatible with Scopt 3

### ISSUE THREAD

**Issue by slandelle** [scopt/scopt#298]
Hi @eed3si9n 

Quoting your [post](https://eed3si9n.com/scopt4):

> If you have been using scopt 3, and if source compiles, you should be ok.

I was under the impression that I could upgrade my project to Scopt 4 and that other projects both consuming it and Scopt 3 wouldn't have any issue.

However, it seems that upgrading to Scopt 4 is neither source not binary transparent:

```
java.lang.NoClassDefFoundError: scopt/Zero$
	at io.gatling.app.cli.ArgsParser.parseArguments(ArgsParser.scala:73)
```

Crashing code is [here](https://github.com/gatling/gatling/blob/master/gatling-app/src/main/scala/io/gatling/app/cli/ArgsParser.scala#L73).

Apologies if this code is crap or outdated, it wasn't revisited for a very long time.

Cheers

**Comment by eed3si9n** [comment]
Scopt 4 is mostly source compatible, but it's not binary compatible. The shape of user-facing class `scopt.OptionParser` is kept the same, but the underlying gut was refactored. If Gatling depends on Scopt 3, then all of the Gatling users would also need to use Scopt 3.

**Comment by slandelle** [comment]
OK, thanks for the clarification.
Then, I'm afraid we can't pioneer in Scopt 4 upgrade and have to wait some time for adoption to spread.
Thanks a lot for your hard work!
