### ISSUE TITLE
OptionParser help method returns OptionDefinition[Nothing]

### ISSUE THREAD

**Issue by Sciss** [scopt/scopt#3]
When I came across this question (http://stackoverflow.com/questions/9893075/using-the-help-method-in-the-immutable-scopt-scala-optionparser-2-0-1), I looked into the `OptionParser` class, and it occured to me that the `help` method cannot be used, because it returns a `FlagOptionDefinition[Nothing]`, and since `OptionParser` is invariant in `C`, you end up with an `OptionParser[Nothing]`. I think this can be fixed by creating a `FlagOptionDefinition[C]` instead.

**Comment by eed3si9n** [comment]
#6 by @kxbmap fixed this one too. Added a test to verify it.

**Comment by eed3si9n** [comment]
published 2.1.0.
