### ISSUE TITLE
"help" usage text generation in case of required sub-commands

### ISSUE THREAD

**Issue by normenmueller** [scopt/scopt#30]
Depending on https://github.com/scopt/scopt/issues/29: how to mark these sub-commands to be _required_, such that the synopsis would be similar to 

```
mycli [--version] [--help] <command> [<args>]
```

**Comment by eed3si9n** [comment]
Currently the command example is not customizable, so you are stuck with:

```
Usage: scopt [subA|subB] [options] <args>...
```

if you do it like what I suggested in #29.
Currently the concept of `required()` works at individual option level, so if we used it on a command that means that particular command is now required like `minOccurs(1)`. 
Another thing is if we truly required one of the commands to be there how would it work for `--version`?

**Comment by normenmueller** [comment]
I got your point. Just wanted my client to have a similar synopsis like `man git`, even that `<command>` wrt. `--version`, for example, is not quite right:

```
SYNOPSIS
   git [--version] ... <command> [<args>]
```
