### ISSUE TITLE
Parsing multiple args with minOccurs fails from scopt 3.7.1 onwards

### ISSUE THREAD

**Issue by jamesfielder** [scopt/scopt#312]
While trying to update an application from scopt 3.5.0 to 4.0.1 I discovered an issue with the arg parser implementation. If we define the parser as

```scala
val parserOO = new OptionParser[Config]("test-args") {
    head("Give me dem multiargs :(")
    arg[String]("[source_path...] <target_path>")
      .minOccurs(2)
      .unbounded()
      .action((u, c) => c.copy(args = c.args :+ u))
    help("help").text("prints this usage text")
  }
```

with config

```scala
case class Config(args: Seq[String])
```

and invoke this with `Array("1", "2")` in scopt between 3.5.0 and 3.7.0 `Config(Seq("1", "2"))` is returned correctly. However in 3.7.1 onwards we get the error message

```
Error: Argument [source_path...] <target_path>' must be given 2 times
Try --help for more information.
```

I've reproduced this in a separate project [here](https://github.com/jamesfielder/scopt-args-bug).

Removing the `minOccurs(2)` call from the parser definition fixes the bug for all the versions of scopt I have tested, however I do need to assert there are at least 2 arguments in the application I am working on so this isn't a work around unfortunately!

**Comment by eed3si9n** [comment]
Thanks for the detailed bug report!

I guess the bug is hiding somewhere here? - https://github.com/scopt/scopt/compare/v3.7.0...v3.7.1

**Comment by jamesfielder** [comment]
Had a go at fixing this, looking between the tags made it quite obvious where to start!
