### ISSUE TITLE
How to run an application?

### ISSUE THREAD

**Issue by olgakabirova** [scopt/scopt#313]
Hi,
I can run my application only inside sbt with command: 
`run --foo 2 -b 1`

Ideally I would like to run my application in terminal like this: 
`myapp --foo 2 -b 1 `
or this script :
`./myapp --foo 2 -b 1 `

Could you explain me, please, how to do it?

**Comment by eed3si9n** [comment]
What you're asking is basically how to create a standalone command line app in Scala. That really has nothing to do with scopt, and there are several ways of doing it depending on how nice you want it to be.

1. [sbt-native-packager](https://sbt-native-packager.readthedocs.io/en/latest/archetypes/java_app/index.html). This is the most standard route, and probably the quickest. It would grab all the JAR files and generate a Bash script that would call them together.
2. [sbt-native-image](https://github.com/scalameta/sbt-native-image). This plugin generates a _native image_ using GraalVM, so it's quick to startup, but you'd need to use GitHub Actions to generate image for macOS, Linux, and Windows separately.
3. [sbt-assembly](https://github.com/sbt/sbt-assembly#prepending-a-launch-script). If you want to create a single-file JAR that still works on all OSes, you can use sbt-assembly.
