### ISSUE TITLE
whitespace seperation for flags with multiple inputs

### ISSUE THREAD

**Issue by ygoeksu** [scopt/scopt#315]
When using this cli and the git cli, it is hard for me to remember which one uses whitespaces and which one uses commas to seperate input for flags.
The code looks something like this:

```scala
cmd("up")
          .action((_, c) => c.copy(command = "up"))
          .text("info")
          .children(
            opt[Seq[String]]("numbers")
              .text("One or more numbers (comma separated without spaces)")
              .action((value, c) => config.copy(tnumbers = value))
          )
```

Is there a way to generate a flag, where the input parameters are given with whitespace seperation, instead of comma seperation?
E.g `--up text1 text2 text3` , instead of `--up text1,text2,text3`
Thanks in advance :)

**Comment by eed3si9n** [comment]
Yea. I was somewhat skeptical about the idea of supporting `Seq[A]` as option in https://github.com/scopt/scopt/issues/53.

Then I got a pull request https://github.com/scopt/scopt/pull/56, and the PR author said Hadoop uses comma-separated list - https://hadoop.apache.org/docs/r1.0.4/api/org/apache/hadoop/util/GenericOptionsParser.html

> When using this cli and the git cli, it is hard for me to remember which one uses whitespaces and which one uses commas to seperate input for flags.

Do you have an example of `git` CLI using whitespace to separate command-line _options_, not subcommand arguments?

**Comment by ygoeksu** [comment]
I think an example for this would be the git restore --staged "<file>" ... comand
As far as I understood it the code for this should be somewhere there: https://github.com/git/git/blob/7e391989789db82983665667013a46eabc6fc570/builtin/checkout.c

**Comment by eed3si9n** [comment]
I don't think `git restore` is a good example.

```sh
$ git restore --help | head
GIT-RESTORE(1)                    Git Manual                    GIT-RESTORE(1)



NAME
       git-restore - Restore working tree files

SYNOPSIS
       git restore [<options>] [--source=<tree>] [--staged] [--worktree] [--] <pathspec>...
       git restore [<options>] [--source=<tree>] [--staged] [--worktree] --pathspec-from-file=<file> [--pathspec-file-nul]
```

`--staged` is just a flag. The other parts are not argument to the option, but it's an argument to the program, which scopt support.

I'm closing this as won't fix for now.
