### ISSUE TITLE
Locale option is not working in Calendar parsing

### ISSUE THREAD

**Issue by fangpings** [scopt/scopt#318]
When I was trying to create a customized calendar read with `calendarRead ` function it was not working as expected. Looks like the argument `locale` is not used here

https://github.com/scopt/scopt/blob/34548cf739fee1cecd7daf056a3b334cf4d68022/jvm/src/main/scala/PlatformReadInstances.scala#L19-L25

**Comment by eed3si9n** [comment]
Thanks for the report and PR!

I don't remember what I was thinking in when I wrote https://github.com/scopt/scopt/commit/fe3043013b79a095097fecfe3da3eb5f3efbc67f, but my guess is that it wasn't for the timezone, but for [java.util.Calendar.getInstance(Locale)](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#getInstance-java.util.Locale-) instead. I'm also not sure what the impact would be if we suddenly changed this implementation after 8 years, so likely the safe thing to do is let it be.

**Comment by fangpings** [comment]
Yes that actually makes sense. Should we do
```
val fmt = new SimpleDateFormat(pattern, locale) 
val c = new GregorianCalendar(locale)
```
in order to make this locale argument meaningful?

**Comment by eed3si9n** [comment]
Sure but only if the default behavior would be unchanged.

**Comment by fangpings** [comment]
Looks like if no Locale is specified for `SimpleDateFormat ` and  `GregorianCalendar` then default one is used so default behavior should remain unchanged. 

BTW is it OK to add a overloading function that works with TimeZone like the one I raised in the PR instead of changing the current one? Feel like it's useful :).

**Comment by eed3si9n** [comment]
I don't think it's safe to add a method to a trait unfortunately. I should've changed it to abstract class.

**Comment by fangpings** [comment]
Oh that's a trait. OK I'll keep it as is then. Thanks for the reply!
