### ISSUE TITLE
Request for a new release with latest changes on `develop` branch

### ISSUE THREAD

**Issue by jacobenget** [scopt/scopt#320]
I have a use case that would directly benefit from the feature added in [this PR](https://github.com/scopt/scopt/pull/317) a few months ago.  I notice though that a new official release of `scopt` hasn't happened since that PR was merged, and so there are no `scopt` artifacts in the public with this feature.

So I'm hoping for a new release (`4.1.0` I imagine) of `scopt` to happen. Is there anything I can do to help that along?

**Comment by cstroe** [comment]
I would advocate also including a fix for #264 in the next release.

**Comment by eed3si9n** [comment]
https://github.com/scopt/scopt/releases/tag/v4.1.0 is out.
