### ISSUE TITLE
Default options not visible

### ISSUE THREAD

**Issue by pferrel** [scopt/scopt#40]
The case class, you call "Config" in the example will have default values for various options. My help text mentions these in the form:

```
     note("\nSpark config options:")
     opt[String]("sparkExecutorMem") abbr ("sem") action { (x, options) =>
       options.copy(sparkExecutorMem = x)
     } text ("Max Java heap available as \"executor memory\" on each node (optional)." + "
         " Default: 2g")
```

It would be much better if the default options could be printed in the help text rather than relying on the text to reflect the options when they change. But the case class cannot be referenced by member (afaik) and the options object does not contain the defaults yet. Maybe there is a way to do this that I haven't found but it would look something like this:

```
    } text ("Max Java heap available as \"executor memory\" on each node (optional)." + "
         " Default: " + someValInScope.sparkExecutorMem)
```

Where someValInScope contains the default values before the parsed option is set.

**Comment by eed3si9n** [comment]
I think it's simpler if you just define `someValInScope` rather than trying to make scopt too clever about what it accepts as config class.

``` scala
object DefaultValues {
  def sparkExecutorMem: String = "1G"
}
case class Config(sparkExecutorMem: String = DefaultValues.sparkExecutorMem)
```

**Comment by pferrel** [comment]
I agree and this is exactly what I ended up doing. Chose not to use case class for Config because the total could exceed 22. Sorry should have closed this
