### ISSUE TITLE
Case class too limiting

### ISSUE THREAD

**Issue by pferrel** [scopt/scopt#42]
I need 23 parameters the Config as a case class will not support that. Tried using mutable parsing but you still seem to need a case class. 

In general the Config needs to be better documented, there is no example afaik that shows how to create one. I fumbled around until I found a way that works but now I'm stuck again.

**Comment by eed3si9n** [comment]
scopt on its own doesn't assume case class: you should be able to use `HList`, `Map[String, Any]` or anything you want in there.

**Comment by pferrel** [comment]
Great, thanks for the quick reply! 

I'm fairly new to Scala so apologies, 

It was hard to see that the action block needs to return the instance of your options container. So I was doing c.input = x, which would work but breaks the compile because it returns Unit. The compiler error message was really confusing me but when I changed it to:

```
   opt[String]('i', "input") required() action { (x, c) =>
      c.input = x
      c
    } text ("Input path, may be a filename, directory name, or comma delimited list of HDFS supported URIs (required)")
  ...
```

everything seems cool. Just needed to return `c` 

BTW c is a var and all instance data is var, Does it matter whether I use mutable or immutable parsing?

**Comment by eed3si9n** [comment]
Using `var` is a bad style of writing Scala unless you're going for some specific reason. If you're using mutable config (including `var`), mutable parser makes shorter and easier to read code.

**Comment by seeruk** [comment]
I know this is an incredibly old issue, but I'd been trying to look into how scopt handled state as I'm attempting to learn Scala and develop my functional programming skills. So, I've been reading a lot about  things like pure functions, referential transparency, and immutability.

This had led me to poking around in the scopt source code to figure out how it worked "immutably", and initially I had thought it was just from avoiding using `var`. Then I noticed the mutable collections being used, and it led me to this issue.

Why is it that using `var` is bad, but using the mutable collections is still okay? Can you think of a way to make scopt more referentially transparent (the thing that got me thinking about this is that if a function doesn't return anything, it mustn't be referentially transparent, so how could the parser's builder functions be referentially transparent?)?
