### ISSUE TITLE
minOccurs doesn't work with arg

### ISSUE THREAD

**Issue by codingismy11to7** [scopt/scopt#45]
I'm using an OptionParser "Files" argument that's almost exactly like the example docs. It's the last argument in the OptionParser besides help & version.

This works:

``` scala
arg[File]("<file>...") unbounded() text "File(s) to update" action { (f, c) ⇒ c.copy(files = c.files :+ f)}
```

However, I'm trying to make the argument required:

``` scala
arg[File]("<file>...") minOccurs 1 text "File(s) to update" action { (f, c) ⇒ c.copy(files = c.files :+ f)}
```

When I run the second version with two arguments, I get

```
Error: Unknown argument '/tmp/blah2'
Try --help for more information.
```

**Comment by codingismy11to7** [comment]
I'm dumb - unbounded() already requires the argument to be specified. Regardless, is the behavior I'm seeing expected? Please close if so

**Comment by eed3si9n** [comment]
Maybe my writing isn't clear here https://github.com/scopt/scopt#arguments:

> By default, arguments accept a single value and are required.
> 
> ### Occurrence
> 
> Each opt/arg carries occurrence information `minOccurs` and `maxOccurs`. `minOccurs` specify at least how many times an opt/arg must appear, and `maxOccurs` specify at most how many times an opt/arg may appear.
> 
> Occurrence can be set using the methods on the opt/arg:
> 
> ``` scala
> opt[String]('o', "out") required()
> opt[String]('o', "out") minOccurs(1) // same as above
> arg[String]("<mode>") optional()
> arg[String]("<mode>") minOccurs(0) // same as above
> arg[String]("<file>...") optional() unbounded()
> arg[String]("<file>...") minOccurs(0) maxOccurs(1024) // same as above
> ```

Just saying `arg[File]("<file>")` has `minOccurs` of 1 and `maxOccurs` of 1 by default. This allows one and only one argument (no more or no less). Adding `minOccurs 1` doesn't change anything. Adding `unbounded()` changes `maxOccurs` to 1024, so you can have two arguments.

**Comment by codingismy11to7** [comment]
Sorry about that, thank you. It's obvious, I should have re-read the docs.
