### ISSUE TITLE
allow duplicate options 

### ISSUE THREAD

**Issue by pferrel** [scopt/scopt#51]
I'd like an option that defines params for an engine like hadoop or spark of the form:

```
-D:spark.max.cores=7
```

This works fine with `opt[(String, String)]("define") abbr ("D")...` but it implies there may be more than one -D option on the CLI like:

```
-D:spark.max.cores=7
-D:spark.executor.memory=6g
```

This is not allowed afaict. Any way to get around this?

**Comment by eed3si9n** [comment]
Try

``` scala
opt[(String, String)]("define") abbr ("D") unbounded() ...
```

https://github.com/scopt/scopt#occurrence

**Comment by pferrel** [comment]
You've thought of everything, thanks
