### ISSUE TITLE
Argument List paired with opts

### ISSUE THREAD

**Issue by AlessandroEmm** [scopt/scopt#53]
Hey there

Maybe I'm missing something, but is there a way to combine opts and args like:

scoptporgram -p x=XX,z=ZZ -n z,d,a 

?

Thanks!

**Comment by eed3si9n** [comment]
I'm not clear what those comma separated list is supposed to mean.

Do you know of any well known Unix command line program or other command line parsing library that implements them?

**Comment by AlessandroEmm** [comment]
I can't think of an CLI-app where I used this right now, but it should be along the lines of the -p Parameter here http://stackoverflow.com/a/8156311/728178 

Python's builtin argparse does also allow for using the same parameter multiple times thus -p Example1 -p Example2 which results in ["Example1", "Example2"]
But frankly i'd prefer the first approach.

I'll try to bring up a better example out of the GNU World of Tools.

**Comment by eed3si9n** [comment]
> As it parses the command line
> 
> ``` python
> -f foo.txt -p 1 -3.5 4 -fbar.txt
> ```

![skeptical face](http://4.bp.blogspot.com/-VmSyy__XZhk/VFayObt9L5I/AAAAAAAAEIY/YYqc8zzhj9c/s1600/tommy.gif)

**Comment by AlessandroEmm** [comment]
So? :+1:  

Seems like more classical tools like mkdir use the {val1, val2, val3 } Syntax.
http://en.wikipedia.org/wiki/Mkdir#Examples

Anyway maybe it would have been easier if i had been asking for a:

```
opt[Seq(Int)]('f', "foo")  
Or
opt[Seq(Int, String)]('kv', "k-v") 
```

**Comment by eed3si9n** [comment]
Also what exactly is your use case for it? scopt already supports option grouping like `-fb` to mean `--foo --bar`.

**Comment by eed3si9n** [comment]
> And an even more powerful command, creating a full tree at once **(this however is a Shell extension, nothing mkdir does itself)**

insert another skeptical face

**Comment by eed3si9n** [comment]
If you want you could just implement `Read` instance for `Seq` similar to what I do for `Option`. https://github.com/scopt/scopt/blob/1675d29d3cacce5eeaec256c6d6eb7d85ac02dd1/src/main/scala/scopt/options.scala#L52-L59

**Comment by AlessandroEmm** [comment]
Well my use case is passing a key-val List of Port=Configuration for building up a List of Webserver Instances with the attached configurations as a File, but as the Configuration is optional I'd like to allow passing Ports without an attached configuration as well. Obviously I could allow for handing fake configuration, but that doesn't make a nice CLI-Interface. :-)

Yeah I see, maybe, the configuration I would like to pass is just too complex/unnatural for a CLI.
