### ISSUE TITLE
Could you deploy 3.3.0 to maven?

### ISSUE THREAD

**Issue by rishter** [scopt/scopt#58]
We've been using Maven for scopt, but I just realized that 3.2.0 doesn't support Reads[Map]. Right now, as a strawman, I took the implementation of MapRead to implement my own read, but it would be great to have the latest version of the project! Thanks

**Comment by eed3si9n** [comment]
It should be there: http://search.maven.org/#artifactdetails%7Ccom.github.scopt%7Cscopt_2.11%7C3.3.0%7Cjar

**Comment by rishter** [comment]
thanks!

Rishikesh Tirumala
