### ISSUE TITLE
version 3.3.0 sbt assembly does not work 

### ISSUE THREAD

**Issue by dunajevas** [scopt/scopt#64]
Hi,

I'm using scala 2.11.1/2.10.4 and scopt 3.3.0. I use sbt assembly to get fat jar with all classes in my source code. Running this jar throws this error

`Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.IntRef.create(I)Lscala/runtime/IntRef;`

when I try to decompose my jar file I can see that `create` method is there for `IntRef` class. Do you have any ideas why this might be happening?

**Comment by gna-phetsarath** [comment]
I had the same problem and then saw this: http://stackoverflow.com/questions/23434393/scala-option-parsing-with-scopt

The problem was resolved once I switched back to Scala 2.10.4

**Comment by eed3si9n** [comment]
ok, so this is likely a Scala version mismatch?
I'm closing this for now.
