### ISSUE TITLE
Consider supporting equals sign in long opt format

### ISSUE THREAD

**Issue by ibalashov** [scopt/scopt#67]
E.g. in addition to `--configFile file` would also be great to support `--configFile=file`, which is also quite common.

**Comment by eed3si9n** [comment]
It might be tricky because `=` is part of the syntax for some of the option types:

```
  --max:<libname>=<max>
        maximum count for <libname>
  --kwargs k1=v1,k2=v2...
        other arguments
```

Do you have particular examples (either with your app or commonly used command line app) where using `=` is advantageous or necessary?

**Comment by ibalashov** [comment]
Well, I would not say using `=` is either advantageous or necessary. It's just both notations are common, and, for example, I, as a developer, would like to make our sysop team a tiny bit happier when they not type `--a=b`, and get an error.

As far as examples go, I would say this notation is common in many unix commands. The first one which came to mind and having long-opts format, was `grep`:

```
$ man grep
...
-B num, --before-context=num
             Print num lines of leading context before each match.  See also the -A and -C options.

```

**Comment by ibalashov** [comment]
> It might be tricky because = is part of the syntax for some of the option types

Looks like quoting the value part containing meta-chars and equals sign could solve this.

**Comment by maizy** [comment]
i'm trying to implement that here - #87
