### ISSUE TITLE
How to recognize optional params

### ISSUE THREAD

**Issue by numbnut** [scopt/scopt#71]
Is it possible to find out whether a value was set or not after parsing the args?
Why is a optional parameter not of the type Option[_]?
As far as I know the only way to achieve this is to define a default value and check whether the default value is set, but that fails when the same value as the default value is set.
I Hope you get my point.

Thanks!

**Comment by eed3si9n** [comment]
> Is it possible to find out whether a value was set or not after parsing the args?
> Why is a optional parameter not of the type Option[_]?

scopts generates a parser, so you can think of the `opt[Int]('f', "foo")` as `Option[Int]` that you're writing a `foreach` on. If you like to use `Option[Int]` just put that in your configuration case class with default value of `None`.

**Comment by numbnut** [comment]
Thanks for your advice. I tried that but I didn't realize that I have to provide a implicit.

``` Scala
implicit val optionRead: scopt.Read[Option[String]] = scopt.Read.reads(Some(_))
```

Now everything works fine. Thanks for the fast reply.
