### ISSUE TITLE
Provide ability to override call to `sys.exit`

### ISSUE THREAD

**Issue by metasim** [scopt/scopt#73]
While it's more of an edge case, I'm writing tests that drive command line tools using `scopt` by passing args and testing the resulting output. This includes intentionally passing bad argument lists to illicit an error. Unfortunately, the `help` and `version` generators call `sys.exit` explicitly, terminating the JVM. Would you consider a feature whereby a settable function is called in `OptionParser` instead, with the default implementation calling `sys.exit`?

**Comment by metasim** [comment]
PS: I should have asked, is this something you would consider via a PR?

**Comment by eed3si9n** [comment]
Sounds like a reasonable request/PR candidate.

**Comment by metasim** [comment]
@eed3si9n How's the PR look to you?

**Comment by eed3si9n** [comment]
Thanks for the reminder. Added minor comment.

**Comment by stuhood** [comment]
Hey gang: one comment while you're looking at this code.

Currently scopt doesn't `exit(1)` when it receives an invalid option, but it should. The "help flag" case should still result in a clean `exit(0)`.

**Comment by eed3si9n** [comment]
so the newly added `terminate` should accept `Either[String, Unit]` or something like that and turn it into `1` and `0`.

**Comment by metasim** [comment]
How would the implementer of `terminate` know how to interpret the `String` side, or what to do with it? Based on the current implementation, any message would have already been printed out. What would be the down side to just `terminate(isParseError: Boolean)`?

**Comment by betehess** [comment]
What is the status of that issue?

**Comment by eed3si9n** [comment]
Done - http://notes.implicit.ly/post/139364514204/scopt-340

**Comment by metasim** [comment]
@eed3si9n Thanks for wrapping this up. Sorry I dropped the ball on implementing the `Either` tweak. I appreciate you just doing it.
