### ISSUE TITLE
Read[File] should verify given file exists (?)

### ISSUE THREAD

**Issue by danxmoran** [scopt/scopt#78]
Should the implicit [`Read[File]`](https://github.com/scopt/scopt/blob/scopt3/src/main/scala/scopt/options.scala#L49) value defined by scopt check that paths given as input actually point to existing files?

I recently stumbled across scopt and used it to make my life much easier in a programming challenge (thanks!), but I was surprised to see during testing that if I passed a nonsense path into a `File` argument / option scopt would happily pass it along to my application.  I was expecting the reader to perform a check similar to the implicit definition of [`Read[Boolean]`](https://github.com/scopt/scopt/blob/scopt3/src/main/scala/scopt/options.scala#L26) and fail if a nonexistent file was passed as input.

I ended up solving my issue by defining a new implicit `Read[File]` in the scope of my `OptionParser`.  I'd be happy to set up a PR to move my changes into the scopt core, but I wanted to check for interest here before putting in the time to update the existing UTs.

**Comment by wookietreiber** [comment]
@danxmoran I recommend to think of `Read[File]` being more generic, i.e. it can be used for files to be read from or written to or maybe even something else.

From your comment, I assume you want to read from files or maybe modify them in place, anyway, you expect the file to already exist. You can handle this via a simple validation:

``` scala
package org.example

import java.io.File

object Main extends App {

  case class Config(files: List[File] = Nil)

  val parser = new scopt.OptionParser[Config]("app") {
    arg[File]("<file1> <file2> ...") optional() unbounded() action { (file, config) =>
      config.copy(files = file :: config.files)
    // THIS IS THE IMPORTANT BIT
    } validate { file =>
      if (file.exists) success else failure(s"$file does not exist.")
    }
  }

  parser.parse(args, Config()) match {
    case Some(config) =>
      config.files foreach println

    case None =>
      sys exit 1
  }
}
```

Executed from within sbt, I give you a failing and a successful example:

```
$ runMain org.example.Main /path/to/some-file-a /path/to/some-file-b
[info] Running org.example.Main /path/to/some-file-a /path/to/some-file-b
Error: /path/to/some-file-a does not exist.
Error: /path/to/some-file-b does not exist.
Usage: app [<file1> <file2> ...]

  <file1> <file2> ...


Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-1c"
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:runMain for the full output.
[error] (compile:runMain) Nonzero exit code: 1
[error] Total time: 0 s, completed Dec 24, 2015 11:25:46 AM
```

```
$ runMain org.example.Main src src/main/scala/example.scala 
[info] Running org.example.Main src src/main/scala/example.scala
src/main/scala/example.scala
src
[success] Total time: 1 s, completed Dec 24, 2015 11:26:15 AM
```

**_Note:**_ Would scopt check for this automatically, you would not be able to supply files where the app should write to, because they would need to exist in advance of the app being executed.

**Comment by eed3si9n** [comment]
What @wookietreiber said.
