### ISSUE TITLE
Add default value to `optional` for usage 

### ISSUE THREAD

**Issue by Woodz** [scopt/scopt#82]
Hello,
Whilst using scopt with some optional command line arguments, I found myself repeating myself by putting the text "Defaults to xxxx if not specified." in the `text` element of each optional option. Perhaps it would be nicer if  `optional()` took a parameter that was the default value so this could automatically populate the usage?

e.g. instead of
`arg[String]("out") text "The output directory. Defaults to '.' if not specified" optional()`
this could be made nicer with
`arg[String]("out") text "The output directory" optional(".")`
and still print out the same usage.

Cheers!

**Comment by eed3si9n** [comment]
I don't know about this one.
- I don't think `optional(".")` is super intuitive.
- Maybe `defaults(".")`, but that's also misleading unless I enforce that somehow.
- If you want to reduce the boilerplate perhaps you can define some function and use `s"""The output directory. ${defaultsTo(".")}"""`
