### ISSUE TITLE
Add support for positional arguments

### ISSUE THREAD

**Issue by rogue-one** [scopt/scopt#88]
Add support for positional arguments which doesn't involve flags. for eg

```
binary_package cmd --opt1 value1 --opt2 value2
```

here `cmd` is a positional argument.

**Comment by rogue-one** [comment]
this feature is seemed to be supported already

**Comment by atronchi** [comment]
The 'command' feature seems to be the only type of positional argument supported currently, but is not a general implementation of positional arguments. e.g. if I want to define the first positional argument to be `date` which can take on yyyyMMdd like integer values (e.g 20170701), this does not seem to be possible currently using scopt. If possible, it's at least not described in the docs that I've seen.

**Comment by atronchi** [comment]
Oh derp, NM. Positional arguments do seem to be supported via the `arg` function.
