### ISSUE TITLE
Reuse existing "String to Type" logic for values from ENV variables (?)

### ISSUE THREAD

**Issue by sthzg** [scopt/scopt#89]
Is it possible to reuse logic implemented in Scopt to parse and validate opt/arg values that aren't passed on the command line? I am thinking about supporting ENV variables to alter the defaults , e.g.

``` scala
case class CliConfig(someint: Int = 5)
// somewhere in the parser
opt[Int]("someint") ...    
```

```
$ myapp                                 # someint = 5
$ MYAPP_SOMEINT=10 myapp                # someint = 10
$ MYAPP_SOMEINT=10 myapp --someint:15   # someint = 15
```

To check for the default I thought about implementing sth. like `envOrDefault(key: String, value: Any)`

``` scala
case class CliConfig(someint: envOrDefault("someint", 5))
```

Now should an ENV variable override the default, is there a way for me to use Scopt's functionality to parse that String representation to its target data type exactly the same way it would do if I had passed it explicitly with the command?

Hope it is understandable :)
Thanks for Scopt!

**Comment by eed3si9n** [comment]
I always thought fallback to Typesafe Config or something like that would be interesting, but environment variables make sense too. You're suggesting essentially a two-stage fallback:
- Use `--someint 15` if present
- Use `MYAPP_SOMEINT` if present
- Use hardcoded default value 5

**Comment by sthzg** [comment]
Yes, exactly, although I am also thinking about a file-based configuration layer. In that sense it would be interesting to have Scopt-API expose its functionality for parsing and validating options, even if their source is not the command line (no matter where they come from, a file, an ENV variable or maybe even a remote API call). So the CL-app-author could do whatever business-logic fits for their certain use case to populate the final set of options.
