### ISSUE TITLE
No termination handler?

### ISSUE THREAD

**Issue by pkolaczk** [scopt/scopt#90]
The documentation says I can override the `terminate` method to avoid calling `sys.exit`. However, there is no `terminate` method in version 3.3.0, and `sys.exit` is hardcoded. Is there any way to workaround this? I need to embed scopt inside some bigger program, and I don't really want it to call sys.exit.

**Comment by betehess** [comment]
@pkolaczk that's a duplicate of #73.

**Comment by metasim** [comment]
@pkolaczk The `terminate` method was added in this PR:

https://github.com/scopt/scopt/pull/74/files

**Comment by eed3si9n** [comment]
Done - http://notes.implicit.ly/post/139364514204/scopt-340
