### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by andreaferretti** [scopt/scopt#92]
It seems that the repository has some new stuff, such as `durationRead`, that is not present in the Maven build. Would it be possible to publish a new version on Maven?

**Comment by billonahill** [comment]
+1 for a new release please. :)

**Comment by eed3si9n** [comment]
Thanks for the ping. I'll look into this today, tomorrow, or this weekend.

**Comment by eed3si9n** [comment]
Done http://notes.implicit.ly/post/139364514204/scopt-340
