### ISSUE TITLE
Version 3.4.0 missing from sonatype repositories

### ISSUE THREAD

**Issue by GreyCat** [scopt/scopt#99]
Primary documentation states that installation requires the following in `build.sbt`:

```
libraryDependencies += "com.github.scopt" %% "scopt" % "3.4.0"

resolvers += Resolver.sonatypeRepo("public")
```

It tries to search public Sonatype repositories, namely https://oss.sonatype.org/content/repositories/public/com/github/scopt/scopt/3.4.0/scopt-3.4.0.pom

However, as of 2016-02-24, there is nothing at that URL. According to https://oss.sonatype.org/content/repositories/public/com/github/scopt/ , the latest version published at Sonatype is 2.11.

**Comment by slandelle** [comment]
Your url is wrong: the `%%` is to account for the Scala version in the artifactId, as scopt is crossed-published against 2.10 and 2.11.

So the proper urls for the 3.4.0 pom are:
- https://repo1.maven.org/maven2/com/github/scopt/scopt_2.10/3.4.0/scopt_2.10-3.4.0.pom or
- https://repo1.maven.org/maven2/com/github/scopt/scopt_2.11/3.4.0/scopt_2.11-3.4.0.pom 

Note: You should use [http://search.maven.org/](http://search.maven.org/#search%7Cga%7C1%7Cscopt) to search for artifacts.

**Comment by eed3si9n** [comment]
Thanks @slandelle. I'm closing this issue.

**Comment by slandelle** [comment]
@eed3si9n You're welcome. Thanks for your great work!

**Comment by GreyCat** [comment]
Got it working, thanks for a very prompt response, guys! Sorry for the mess :)
